import js from "@eslint/js";
import globals from "globals";
import react from "eslint-plugin-react";
import {defineConfig} from "eslint/config";

export default defineConfig([
    {
        files: ["**/*.{js,mjs,cjs,jsx}"],
        plugins: {js, react},
        extends: ["js/recommended"],
        languageOptions: {
            globals: {...globals.browser, ...globals.node},
            parserOptions: {ecmaFeatures: {jsx: true}},
        },
        settings: {react: {version: "detect"}},
        rules: {
            "no-debugger": "warn",
            "no-console": "warn",
            "array-callback-return": "error",
            "arrow-body-style": ["error", "as-needed"],
            "consistent-return": "error",
            curly: ["error", "all"],
            "default-param-last": "error",
            "dot-notation": "error",
            eqeqeq: ["error", "always"],
            "no-bitwise": "error",
            "no-empty-pattern": [
                "error",
                {
                    allowObjectPatternsAsParameters: true,
                },
            ],
            "no-negated-condition": "error",
            "no-param-reassign": "error",
            "no-return-assign": "error",
            "no-sequences": "error",
            "no-shadow": "error",
            "no-throw-literal": "error",
            "no-undef-init": "error",
            "no-unneeded-ternary": "error",
            "no-unused-expressions": "error",
            "no-unused-vars": [
                "error",
                {
                    argsIgnorePattern: "_+",
                    ignoreRestSiblings: true,
                },
            ],
            "no-useless-computed-key": "error",
            "no-useless-rename": "error",
            "no-useless-return": "error",
            "no-var": "error",
            "prefer-arrow-callback": "error",
            "prefer-const": "error",
            "prefer-destructuring": ["error", {array: false, object: true}],
            "prefer-object-has-own": "error",
            "prefer-template": "error",
            "react/destructuring-assignment": "error",
            "react/display-name": "error",
            "react/function-component-definition": "error",
            "react/hook-use-state": "error",
            "react/jsx-child-element-spacing": "error",
            "react/jsx-closing-bracket-location": "error",
            "react/jsx-closing-tag-location": "error",
            "react/jsx-curly-brace-presence": [
                "error",
                {
                    props: "never",
                    children: "never",
                    propElementValues: "always",
                },
            ],
            "react/jsx-curly-newline": "error",
            "react/jsx-curly-spacing": ["error", {when: "never", children: true}],
            "react/jsx-equals-spacing": "error",
            "react/jsx-filename-extension": ["error", {allow: "as-needed"}],
            "react/jsx-first-prop-new-line": ["error", "multiline"],
            "react/jsx-fragments": "error",
            "react/jsx-indent-props": "error",
            "react/jsx-indent": "error",
            "react/jsx-key": "error",
            "react/jsx-no-comment-textnodes": "error",
            "react/jsx-no-duplicate-props": "error",
            "react/jsx-no-target-blank": "error",
            "react/jsx-no-undef": "error",
            "react/jsx-no-useless-fragment": "error",
            "react/jsx-props-no-multi-spaces": "error",
            "react/jsx-tag-spacing": [
                "error",
                {
                    closingSlash: "never",
                    beforeSelfClosing: "always",
                    afterOpening: "never",
                    beforeClosing: "never",
                },
            ],
            "react/jsx-uses-react": "error",
            "react/jsx-uses-vars": "error",
            "react/jsx-wrap-multilines": "error",
            "react/no-array-index-key": "error",
            "react/no-children-prop": "error",
            "react/no-danger-with-children": "error",
            "react/no-deprecated": "error",
            "react/no-direct-mutation-state": "error",
            "react/no-find-dom-node": "error",
            "react/no-is-mounted": "error",
            "react/no-object-type-as-default-prop": "error",
            "react/no-render-return-value": "error",
            "react/no-string-refs": "error",
            "react/no-unescaped-entities": "error",
            "react/no-unknown-property": "error",
            "react/no-unsafe": "error",
            "react/no-unstable-nested-components": "error",
            "react/prop-types": "off", // TODO Add in the future
            "react/react-in-jsx-scope": "error",
            "react/require-render-return": "error",
            "react/self-closing-comp": [
                "error",
                {
                    component: true,
                    html: true,
                },
            ],
        },
    },
    {
        files: ["geographic_data/*"],
        rules: {
            "no-console": "off",
        },
    },
]);
